spring:
  application:
    name: register-center
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    registry-fetch-interval-seconds: 5
  server:
    enable-self-preservation: false
  instance:
    hostname: 127.0.0.1

