spring:
  application:
    name: register-center
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 5
  server:
    enable-self-preservation: false

